<main role="main" class="container">
  <div class="d-flex justify-content-between flex-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1>
      Scholarship Applications: <small class="text-muted"><?=$data['scholarship_year']?></small>
    </h1>
  </div>
  <div>
    <h2>Student Information</h2>
    <p>Fill out as much as you can.</p>
    <form id="studentForm" method="post">
      <div class="form-row">
        <div class="form-group col">
          <label for="first_name">First Name</label>
          <input v-model="student.first_name" type="text" class="form-control" name="first_name" placeholder="First name" required>
        </div>
        <div class="form-group col">
          <label for="last_name">Last Name</label>
          <input v-model="student.last_name" type="text" class="form-control" name="last_name" placeholder="Last name" required>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col">
          <label for="znumber">Z-number</label>
          <input v-model="student.znumber" type="text" class="form-control" id="znumber" name="znumber" placeholder="Z12345678" required>
        </div>
        <div class="form-group col">
          <label for="email">Email address</label>
          <input v-model="student.email" type="email" class="form-control" id="email" name="email" placeholder="name@fau.edu" required>
        </div>
      </div>
      <qualifier-input v-for="qualifier in qualifiers" :key="qualifier.id"
        :qualifier="qualifier"
        v-model="student.qualifications[qualifier.id]"
      >
      </qualifier-input>
      <button type="submit" class="btn btn-primary mb-3">Continue</button>
    </form>
  </div>
</main>
<script>
var student = <?=isset($data['student']) ? json_encode($data['student'], JSON_NUMERIC_CHECK) : "{}";?>;
var qualifiers = <?=json_encode($data['qualifiers'], JSON_NUMERIC_CHECK);?>;
</script>