<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../../../favicon.ico"> -->

    <title><?= $data['title'] ?> <?= $data['subtitle'] ?></title>

    <!-- Core CSS -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous" />
    <!-- Sticky Footer! -->
    <link href="<?=$data['baseUrl']?>css/sticky_footer.css" rel="stylesheet" />    

    <!-- Custom styles for this template -->
    <?php if(isset($data['styles'])){
      foreach ($data['styles'] as $style): ?>
        <link href="<?=$data['baseUrl']?>css/<?=$style?>" rel="stylesheet">    
      <?php endforeach; 
    }?>

  </head>
  <body>
    <?php if(isset($data['part'])){
      foreach($data['part'] as $bodyPart){
        echo $this->fetch($bodyPart['template'], $bodyPart['data']);
      }
    } ?>
    <footer class="container-fluid">
      <span class="text-muted">Copyright © 2015-2018 FAU Office of Student Financial Aid. All rights reserved.</span>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

    <!-- Custom scripts for this template -->
    <?php if(isset($data['scripts'])){
      foreach ($data['scripts'] as $script): ?>
        <script src="<?=$data['baseUrl']?>js/<?=$style?>" rel="stylesheet" /> 
      <?php endforeach; 
    }?>
  </body>
</html>