<main role="main" class="container mt-3">
  <h1 class="mb-1">Login</h1>
  <?php if(isset($attempt) && $attempt > 0): ?>
    <div class="alert alert-danger mt-3" role="alert">
      Invalid Username/Password.
    </div>
  <?php endif;?>
  <form method="post">
    <div class="form-group">
      <label for="name">Username</label>
      <input type="text" class="form-control" name="name" id="name" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" name="password" id="password" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</main>