<?= $this->fetch("/components/header.phtml"); ?>
<?php include "components/header.phtml"; ?>
<?php print_r($this->getAttributes());?>
<main role="main" class="container">
  <?php if(isset($attempt) && $attempt > 0): ?>
    <div class="alert alert-danger" role="alert">
      Invalid Username/Password.
    </div>
  <?php endif;?>
  <h1 class="mb-1">Login</h1>
  <form method="post">
    <div class="form-group">
      <label for="name">Username</label>
      <input type="text" class="form-control" name="name" id="name" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" name="password" id="password" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</main>
<?= $this->fetch("/components/footer.phtml", $this->getAttributes()); ?>