<style>
body {
  min-height: 75rem;
  padding-top: 4.5rem;
}
</style>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark shadow">
  <a class="navbar-brand" href="<?=$data['baseUrl']?>admin/"><?=$data['title']?> <?=$data['subtitle']?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link <?= $data['active'] === 'scholarships' ? 'active' : ''?>" href="<?=$data['baseUrl']?>admin/scholarship/">Scholarships</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?= $data['active'] === 'applications' ? 'active' : ''?>" href="<?=$data['baseUrl']?>admin/application/">Applications</a>
      </li>
    </ul>
  </div>
  <button class="btn btn-outline-secondary" href="<?=$data['baseUrl']?>admin/logout/" role="button">Sign Out</button>
</nav>