<style>
body {
  padding-top: 4.5rem;
}
</style>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark shadow">
  <a class="navbar-brand" href="<?=$data['baseUrl']?>admin/">
    <img src="<?=$data['baseUrl']?>img/logo-owl-color.svg" height="40px" class="d-inline-block"/>
    <?=$data['title']?>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link <?= $data['active'] === 'scholarships' ? 'active' : ''?>" href="<?=$data['baseUrl']?>admin/scholarship/">Scholarships</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?= $data['active'] === 'questions' ? 'active' : ''?>" href="<?=$data['baseUrl']?>admin/question/">Questions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?= $data['active'] === 'qualifiers' ? 'active' : ''?>" href="<?=$data['baseUrl']?>admin/qualifier/">Qualifiers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?= $data['active'] === 'applications' ? 'active' : ''?>" href="<?=$data['baseUrl']?>admin/application/">Applications</a>
      </li>
    </ul>
  </div>
  <a class="btn btn-outline-secondary" href="<?=$data['baseUrl']?>admin/logout/" role="button">Sign Out</a>
</nav>