<main role="main" class="container">
  <div class="d-flex justify-content-between flex-nowrap align-items-center pt-3 pb-2 border-bottom">
    <h1 class="h2">Qualifiers</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group">
        <button class="btn btn-primary" href="<?="{$data['baseUrl']}admin/create/scholarship/"?>">New Qualifier</button>
      </div>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Question</th>
        <th scope="col">Type</th>
        <th scope="col">Props</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($data['qualifiers'] as $qualifier): ?>
        <tr>
          <th scope="row"><?=$qualifier->getId()?></th>
          <td><?=$qualifier->getName()?></td>
          <td><?=$qualifier->getQuestion()?></td>
          <td><?=$qualifier->getType()?></td>
          <td>
            <?php foreach($qualifier->getProps() as $name => $val):?>
              <span class="font-weight-bold"><?=$name?>:</span>
              <?=json_encode($val,JSON_NUMERIC_CHECK|JSON_PRETTY_PRINT)?>
            <?php endforeach;?>
          </td>
          <td class="align-middle">
            <a href="#" role="button" class="btn btn-outline-primary">
              Edit
            </a>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>
</main>