<main role="main" class="container">
  <div class="d-flex justify-content-between flex-nowrap align-items-center pt-3 pb-2 border-bottom">
    <h1 class="h2">Questions</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group">
        <a class="btn btn-primary" role="button" href="<?="{$data['baseUrl']}admin/create/question/"?>">
          New Question
        </a>
      </div>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Question</th>
        <th scope="col">Type</th>
        <th scope="col">Props</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($data['questions'] as $question):?>
        <tr>
          <th scope="row"><?=$question->getId()?></th>
          <td><?=$question->getQuestion()?></td>
          <td><?=$question->getType()?></td>
          <td>
            <?php foreach($question->getProps() as $name => $val):?>
              <span class="font-weight-bold"><?=$name?>:</span>
              <?=json_encode($val)?>
            <?php endforeach;?>
          </td>
          <td class="align-middle">
            <a href="#" role="button" class="btn btn-outline-primary">
              Edit
            </a>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>
</main>