<?= $this->fetch("/components/header.phtml"); ?>
<main role="main" class="container">
  <h2>Student Information</h2>
  <p>Fill out as much as you can</p>
  <form method="post">
    <?php
      foreach($qualifiers as $qualifier){
        echo $qualifier->renderInput();
      }
    ?>
    <button type="submit" class="btn btn-primary">Search</button>
  </form>
</main>
<?= $this->fetch("/components/footer.phtml"); ?>