<?php include_once "components/header.phtml"; ?>
<main role="main" class="container">
  <?php if(isset($attempt) && $attempt > 0): ?>
    <div class="alert alert-danger" role="alert">
      Invalid Username/Password.
    </div>
  <?php endif;?>
  <h1 class="mb-1">Login</h1>
  <form method="post">
    <div class="form-group">
      <label for="user">Username</label>
      <input type="text" class="form-control" name="user" id="user" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" name="password" id="password" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</main>
<?php include_once "components/footer.phtml"; ?>