<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../../../favicon.ico"> -->

    <title><?= $title ?> <?= $subtitle ?></title>

    <!-- Core CSS -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="<?=$baseUrl?>/css/sticky_footer.css" rel="stylesheet">    

    <!-- Custom styles for this template -->
    <?php foreach ($styles as $style): ?>
    <link href="<?=$baseUrl?>/css<?=$style?>" rel="stylesheet">    
    <?php endforeach; ?>

  </head>
  <body>