<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../../../favicon.ico"> -->

    <title>FAU Scholarship Application</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="<?=$baseUrl?>/css/sticky_footer.css" rel="stylesheet">
    <style>
      img{
        max-width:270px;
      }
    </style>
  </head>

  <body>
    <header class="container">
      <div class="row justify-content-center">
          <div class="col-4">
            <img src="<?=$baseUrl?>/img/fau_logo.jpg" />
          </div>
      </div>
    </header>